[package]
name = "synctex-sticher"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
flate2 = "1.1.2"
nom = "8.0.0"
nom-language = "0.1.0"
nom-supreme = "0.8.0"
